import { SiteSettings } from "./types";

export const defaultSettings: SiteSettings = {
  id: 1,
  theme_id: "luxury-italian",
  restaurant_name: "De Roma",
  logo_url: null,
  hero_image_url:
    "https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=1800&q=88",
  primary_color: "#E3133D",
  secondary_color: "#171717",
  accent_color: "#F6B94A",
  background_color: "#FFFDFB",
  surface_color: "#FFFFFF",
  text_color: "#171717",
  muted_text_color: "#746C68",
  font_body: "cairo",
  font_display: "changa",
  base_font_size: 16,
  heading_scale: 1,
  border_radius: 24,
  shadow_strength: 0.22,
  header_style: "glass",
  hero_style: "editorial",
  card_style: "soft",
  phone: "0944400150",
  whatsapp: "218944400150",
  address: "طرابلس، ليبيا",
  hours: "يوميًا · 1:00 ظهرًا — 1:00 صباحًا",
  presto_url: null,
  tagline: "بيتزا ومعجنات إيطالية تُحضّر يوميًا وتصل ساخنة داخل طرابلس",
  hero_badge: "طعم إيطالي حقيقي في قلب طرابلس",
  hero_headline: "بيتزا تُخبز بحب،",
  hero_headline_accent: "وتصل ساخنة إلى بابك",
  hero_subheadline:
    "عجينة يومية، مكونات مختارة، وطعم واضح يخلي كل طلب تجربة تستحق التكرار.",
  about_badge: "قصتنا",
  about_title: "نخبز كل قطعة وكأنها أول طلب في اليوم",
  about_body:
    "نهتم بالعجينة قبل كل شيء، ونختار المكونات بعناية، ونحافظ على نفس الجودة في كل مرة. الهدف بسيط: طعم واضح، جبنة حقيقية، وخدمة تستحق الثقة.",
  cta_primary_label: "شاهد المنيو",
  cta_secondary_label: "اطلب عبر واتساب",
  gallery_title: "كل صورة تحكي طعمًا",
  gallery_subtitle: "صور مرتبة ومتناسقة تعرض الأكل والأجواء بدون ازدحام أو أحجام عشوائية.",
  gallery_images: [],
  footer_text: "بيتزا إيطالية بطابع محلي، عجينة يومية، وخدمة توصيل داخل طرابلس.",
};
